networks:
  app:

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    networks:
      - app

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_LISTEN_PORT=8080
    ports:
      - 8080:8080
    networks:
      - app
